### ISSUE TITLE
CoffeeScriptProcessor: Can't have an abstract method in a non-abstract class

### ISSUE THREAD

**Issue by gubespam** [brian428/sencha-grails-asset-pipeline#1]
When using sencha-grails-asset-pipeline plugin 1.0.2 with asset-pipeline plugin version 2.1.5, I get the following error when trying to build the war file:

```
Compilation error: startup failed:
C:\workspace\my-app-grails\plugins\coffee-asset-pipeline-1.8.0\src\groovy\asset\pipeline\coffee\CoffeeScriptProcessor.groovy: 10: Can't have an abstract method in a non-abstract class. The class 'asset.pipeline.coffee.CoffeeScriptProcessor' must be declared abstract or the method 'java.lang.String process(java.lang.String, asset.pipeline.AssetFile)' must be implemented.
 @ line 10, column 1.
   class CoffeeScriptProcessor extends AbstractProcessor {
```

The solution is to change the method signature in CoffeeScriptProcessor from:

```
def process(input, assetFile) {
```

to

```
String process(String input, AssetFile assetFile) {
```

**Comment by gubespam** [comment]
Also need to add `import asset.pipeline.AssetFile`

**Comment by brian428** [comment]
I assume you just submitted this issue to the wrong repository, since an issue with the coffee-asset-pipeline belongs in that project, not this one.

**Comment by gubespam** [comment]
Yeah I realized later that this was actually code form the coffeescript pipeline plugin not the assest-pipeline itself.
